language: ruby
services:
- docker
cache:
- bundler
before_install:
- gem install bundler
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-cpu-checks.gemspec
- gem install sensu-plugins-cpu-checks-*.gem
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"
deploy:
- provider: rubygems
  api_key:
    secure: AyvwPx6XOE0hfd09ji2oRonTECC+zh0sVZByRHtCfulKBNKPM5rph96eR6q0QFz9/dqJev7veAThmxGrEaODE4muMk5CdM5VfaR1i8Fc4e7YmuhnMAZxzi9RsBSE/FpPlXVhJ0kd8AP910SVmBixnDyxlC46zatdKToZELv/YF8=
  gem: sensu-plugins-cpu-checks
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-cpu-checks
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-cpu-checks
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1    
